using System.Collections.Generic;
using UnityEngine;

public enum ShiftMode
{
    None,
    PlannedBlock,
    AdHoc
}

/// <summary>
/// v4.0 — Orchestrates the daily shift calendar on top of the existing
/// PlayerHandoff / BusScheduler / BusManager stack.
///
/// Route generation now uses deterministic, time-based weighted route
/// chances configured directly on this component.
///
/// Higher route weight = higher probability.
/// Weight 0 = route disabled for that time interval.
///
/// The actual calendar is still generated by DailyShiftGenerator.
/// ShiftRunner owns the editable route-chance configuration and passes it
/// into the generator.
///
/// Calendar generation remains deterministic:
///     dayNumber + PLAYER_BUS_ID + preferredRoute
///
/// Therefore the same settings produce the same calendar every time.
/// </summary>
public class ShiftRunner : MonoBehaviour
{
    public static ShiftRunner Instance { get; private set; }


    // ═════════════════════════════════════════════════════════════════
    // PREFERRED ROUTE
    // ═════════════════════════════════════════════════════════════════

    [Header("Preferred Route (optional)")]
    public string preferredRoute = "";


    // ═════════════════════════════════════════════════════════════════
    // ROUTE GENERATION CHANCES
    // ═════════════════════════════════════════════════════════════════

    [Header("Route Generation Chances")]
    [Tooltip(
        "Route weights are relative chances. " +
        "0 = never selected, 1 = normal chance, " +
        "10 = ten times the chance of weight 1. " +
        "Routes not listed in an interval default to weight 1.")] 
    public List<RouteChanceInterval> routeChanceIntervals =
        new()
        {
            new RouteChanceInterval
            {
                intervalName = "00:00 - 04:00",
                startHour = 0,
                endHour = 4,
                routes = new List<RouteChance>()
            },

            new RouteChanceInterval
            {
                intervalName = "04:00 - 08:00",
                startHour = 4,
                endHour = 8,
                routes = new List<RouteChance>()
            },

            new RouteChanceInterval
            {
                intervalName = "08:00 - 12:00",
                startHour = 8,
                endHour = 12,
                routes = new List<RouteChance>()
            },

            new RouteChanceInterval
            {
                intervalName = "12:00 - 16:00",
                startHour = 12,
                endHour = 16,
                routes = new List<RouteChance>()
            },

            new RouteChanceInterval
            {
                intervalName = "16:00 - 20:00",
                startHour = 16,
                endHour = 20,
                routes = new List<RouteChance>()
            },

            new RouteChanceInterval
            {
                intervalName = "20:00 - 00:00",
                startHour = 20,
                endHour = 24,
                routes = new List<RouteChance>()
            }
        };


    // ═════════════════════════════════════════════════════════════════
    // DEBUG
    // ═════════════════════════════════════════════════════════════════

    [Header("Debug")]
    public bool logShiftEvents = true;


    // ═════════════════════════════════════════════════════════════════
    // SCHEDULE
    // ═════════════════════════════════════════════════════════════════

    public List<DailyShiftBlock> todaysSchedule =
        new();

    public int activeBlockIndex = -1;

    public ShiftMode currentMode =
        ShiftMode.None;


    private DailyShiftGenerator _generator;

    private int _pendingRendezvousBusID = -1;


    // ═════════════════════════════════════════════════════════════════
    // SESSION TRACKING
    // ═════════════════════════════════════════════════════════════════

    private bool _sessionActive = false;

    private float _firstBlockScheduledDeparture = -1f;

    private bool _firstBlockOnTime = false;

    private string _sessionRouteForXP = null;

    private int _sessionLapsCompleted = 0;

    private int _sessionBlocksTaken = 0;

    private float _sessionStartRealTime = 0f;

    private float _sessionStartGameMin = 0f;

    private string _pendingRendezvousExpectedRoute = null;

    private int _scheduleDayNumber = -1;


    // ═════════════════════════════════════════════════════════════════
    // SCORING
    // ═════════════════════════════════════════════════════════════════

    private int _sessionPointsGained = 0;

    private int _sessionXPGained = 0;

    private bool _sessionLeveledUp = false;

    private bool _onTimeResolved = false;


    // ═════════════════════════════════════════════════════════════════
    // DAY ROLLOVER
    // ═════════════════════════════════════════════════════════════════

    private bool _regeneratePending = false;

    private bool _subscribedToPlayerHandoff = false;

    private DailyShiftBlock _lastNudgedBlock = null;


    // ═════════════════════════════════════════════════════════════════
    // UNITY
    // ═════════════════════════════════════════════════════════════════

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;

        DontDestroyOnLoad(gameObject);

        _generator =
            new DailyShiftGenerator(
                routeChanceIntervals);
    }


    private void Start()
    {
        if (SimClock.Instance != null)
        {
            SimClock.Instance.OnGameDayRolled +=
                HandleDayRolled;
        }

        LoadOrGenerateSchedule();
    }


    private void OnDestroy()
    {
        if (SimClock.Instance != null)
        {
            SimClock.Instance.OnGameDayRolled -=
                HandleDayRolled;
        }

        if (
            _subscribedToPlayerHandoff &&
            PlayerHandoff.Instance != null)
        {
            PlayerHandoff.Instance.OnShiftEnded -=
                HandlePlayerShiftEnded;

            PlayerHandoff.Instance.OnBlockAdvanced -=
                HandleBlockAdvanced;

            PlayerHandoff.Instance.OnLegArrived -=
                HandleLegArrived;
        }

        SaveProgress();
    }


    private void OnApplicationQuit()
    {
        SaveProgress();
    }


    private void OnApplicationPause(bool paused)
    {
        if (paused)
            SaveProgress();
    }


    // ═════════════════════════════════════════════════════════════════
    // DAY ROLLOVER
    // ═════════════════════════════════════════════════════════════════

    private void HandleDayRolled(int newDay)
    {
        if (currentMode != ShiftMode.None)
        {
            _regeneratePending = true;

            if (logShiftEvents)
            {
                Debug.Log(
                    "[ShiftRunner] Day rolled mid-shift — " +
                    "schedule regen deferred until shift ends.");
            }

            return;
        }

        RegenerateSchedule();
    }


    // ═════════════════════════════════════════════════════════════════
    // LOAD / GENERATE
    // ═════════════════════════════════════════════════════════════════

    private void LoadOrGenerateSchedule()
    {
        int today =
            SimClock.Instance != null
                ? SimClock.Instance.GameDayNumber
                : 0;

        string route =
            string.IsNullOrEmpty(preferredRoute)
                ? null
                : preferredRoute;


        var blocks =
            _generator.Generate(
                today,
                BusScheduler.PLAYER_BUS_ID,
                route);


        var save =
            SaveService.Load();

        var saved =
            save?.assignments.Find(
                a =>
                    a.busID ==
                    BusScheduler.PLAYER_BUS_ID);


        if (
            saved != null &&
            saved.shiftDayNumber == today &&
            saved.preferredRouteAtGen == route &&
            saved.blockStatuses != null &&
            saved.blockStatuses.Count ==
                blocks.Count)
        {
            for (int i = 0;
                 i < blocks.Count;
                 i++)
            {
                blocks[i].completed =
                    saved.blockStatuses[i].completed;

                blocks[i].missed =
                    saved.blockStatuses[i].missed;
            }

            if (logShiftEvents)
            {
                Debug.Log(
                    "[ShiftRunner] Restored today's calendar " +
                    "with saved block progress.");
            }
        }
        else if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] No matching save for today's " +
                "calendar — starting fresh.");
        }


        todaysSchedule =
            blocks;

        _scheduleDayNumber =
            today;

        activeBlockIndex =
            -1;
    }


    // ═════════════════════════════════════════════════════════════════
    // REGENERATE
    // ═════════════════════════════════════════════════════════════════

    public void RegenerateSchedule()
    {
        int today =
            SimClock.Instance != null
                ? SimClock.Instance.GameDayNumber
                : 0;

        string route =
            string.IsNullOrEmpty(preferredRoute)
                ? null
                : preferredRoute;


        todaysSchedule =
            _generator.Generate(
                today,
                BusScheduler.PLAYER_BUS_ID,
                route);

        _scheduleDayNumber =
            today;

        activeBlockIndex =
            -1;


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Regenerated schedule with " +
                $"{todaysSchedule.Count} blocks.");
        }

        SaveProgress();
    }


    // ═════════════════════════════════════════════════════════════════
    // SAVE
    // ═════════════════════════════════════════════════════════════════

    public void SaveProgress()
    {
        var data =
            SaveService.Load()
            ?? new ShiftSaveData();


        data.assignments.RemoveAll(
            a =>
                a.busID ==
                BusScheduler.PLAYER_BUS_ID);


        var statuses =
            new List<BlockStatus>(
                todaysSchedule.Count);


        foreach (var b in todaysSchedule)
        {
            statuses.Add(
                new BlockStatus
                {
                    completed = b.completed,
                    missed = b.missed
                });
        }


        data.assignments.Add(
            new ShiftAssignment
            {
                busID =
                    BusScheduler.PLAYER_BUS_ID,

                fleetNumber = -1,

                shiftDayNumber =
                    _scheduleDayNumber,

                preferredRouteAtGen =
                    string.IsNullOrEmpty(preferredRoute)
                        ? null
                        : preferredRoute,

                currentBlockIndex =
                    Mathf.Max(
                        0,
                        activeBlockIndex),

                blockStatuses =
                    statuses
            });


        SaveService.Save(data);
    }


    // ═════════════════════════════════════════════════════════════════
    // UPDATE
    // ═════════════════════════════════════════════════════════════════

    private void Update()
    {
        if (!_subscribedToPlayerHandoff)
            TrySubscribeToPlayerHandoff();

        CheckPendingRendezvous();

        CheckScheduledBlockArrival();
    }


    private void TrySubscribeToPlayerHandoff()
    {
        if (PlayerHandoff.Instance == null)
            return;


        PlayerHandoff.Instance.OnShiftEnded +=
            HandlePlayerShiftEnded;

        PlayerHandoff.Instance.OnBlockAdvanced +=
            HandleBlockAdvanced;

        PlayerHandoff.Instance.OnLegArrived +=
            HandleLegArrived;


        _subscribedToPlayerHandoff =
            true;


        if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] Subscribed to " +
                "PlayerHandoff events.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // GAP DETECTION
    // ═════════════════════════════════════════════════════════════════

    public bool IsInScheduledWindow(
        float nowAbsoluteMinutes,
        out DailyShiftBlock activeBlock)
    {
        foreach (var block in todaysSchedule)
        {
            if (
                nowAbsoluteMinutes >=
                    block.windowStartMinutes &&
                nowAbsoluteMinutes <=
                    block.windowEndMinutes)
            {
                activeBlock =
                    block;

                return true;
            }
        }


        activeBlock =
            null;

        return false;
    }


    // ═════════════════════════════════════════════════════════════════
    // SCHEDULED BLOCK ARRIVAL / NUDGE
    // ═════════════════════════════════════════════════════════════════

    private void CheckScheduledBlockArrival()
    {
        if (SimClock.Instance == null)
            return;


        float now =
            SimClock.Instance.AbsoluteGameMinutes;


        if (
            !IsInScheduledWindow(
                now,
                out var block))
        {
            return;
        }


        if (
            block.completed ||
            block.missed)
        {
            return;
        }


        if (
            currentMode ==
            ShiftMode.AdHoc &&
            block != _lastNudgedBlock)
        {
            _lastNudgedBlock =
                block;


            if (logShiftEvents)
            {
                Debug.Log(
                    $"[ShiftRunner] Planned block " +
                    $"({block.TimeRangeLabel}, Route {block.routeNumber}) " +
                    "is due — finish your ad-hoc shift on your own terms, " +
                    "or abandon it to take the planned block.");
            }
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // CLAIM ROUTE + BUS
    // ═════════════════════════════════════════════════════════════════

    public void ClaimRouteAndBus(
        string routeNumber,
        string variantLetter,
        TimetableSlot slot,
        int fleetNumber)
    {
        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] PlayerHandoff.Instance is null — " +
                "cannot claim a route.");

            return;
        }


        if (PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Already on duty — " +
                "cannot claim a new route.");

            return;
        }


        if (slot == null)
        {
            Debug.LogWarning(
                $"[ShiftRunner] ClaimRouteAndBus: null slot " +
                $"for Route {routeNumber}.");

            return;
        }


        if (BusSelectMenu.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] BusSelectMenu.Instance is null — " +
                "cannot possess the selected depot bus.");

            return;
        }


        BusSelectMenu.Instance.PossessFleetNumber(
            fleetNumber);

        PlayerHandoff.Instance
            .ReleaseAutoAdoptedSlotForBoardClaim();

        PlayerHandoff.Instance
            .SetFleetNumber(fleetNumber);


        currentMode =
            ShiftMode.PlannedBlock;

        activeBlockIndex =
            -1;

        _sessionRouteForXP =
            routeNumber;

        _sessionActive =
            true;

        _firstBlockScheduledDeparture =
            slot.scheduledDeparture;

        _sessionStartRealTime =
            Time.realtimeSinceStartup;

        _sessionStartGameMin =
            SimClock.Instance != null
                ? SimClock.Instance.AbsoluteGameMinutes
                : 0f;

        _sessionLapsCompleted =
            0;

        _sessionBlocksTaken =
            1;

        _sessionPointsGained =
            0;

        _sessionXPGained =
            0;

        _sessionLeveledUp =
            false;

        _onTimeResolved =
            false;


        if (slot.assignedBusID >= 0)
        {
            int npcBusID =
                slot.assignedBusID;


            var transferred =
                BusScheduler.Instance != null
                    ? BusScheduler.Instance
                        .TransferSlotToPlayer(npcBusID, slot)
                    : null;


            if (transferred != null)
            {
                if (logShiftEvents)
                {
                    Debug.Log(
                        $"[ShiftRunner] Took over Route " +
                        $"{routeNumber} from NPC busID {npcBusID} — " +
                        "remaining chain transferred.");
                }


                PlayerHandoff.Instance
                    .JoinTransferredSlot(
                        routeNumber,
                        variantLetter ?? "",
                        transferred,
                        fromBoard: true);
            }
            else
            {
                Debug.LogWarning(
                    $"[ShiftRunner] TransferSlotToPlayer failed " +
                    $"for Route {routeNumber} " +
                    $"(NPC busID {npcBusID}).");
            }
        }
        else
        {
            PlayerHandoff.Instance
                .JoinRouteWithSlot(
                    routeNumber,
                    variantLetter ?? "",
                    slot,
                    fromBoard: true);
        }


        DriverConsole.Instance?
            .SetJoinFieldsFromBoard(
                routeNumber,
                variantLetter);


        bool actuallyJoined =
            PlayerHandoff.Instance.ShiftState !=
            PlayerHandoff.PlayerShiftState.OffDuty;


        if (actuallyJoined)
        {
            if (logShiftEvents)
            {
                Debug.Log(
                    $"[ShiftRunner] Claimed Route " +
                    $"{routeNumber}{variantLetter} dep " +
                    $"{slot.scheduledDeparture:0.0} — possessing " +
                    $"Fleet #{fleetNumber} from depot, joined via " +
                    "PlayerHandoff.");
            }
        }
        else
        {
            Debug.LogError(
                $"[ShiftRunner] ClaimRouteAndBus: possessed " +
                $"Fleet #{fleetNumber} but PlayerHandoff never left " +
                "OffDuty after JoinRouteWithSlot.");


            _sessionActive =
                false;

            currentMode =
                ShiftMode.None;

            activeBlockIndex =
                -1;

            _sessionRouteForXP =
                null;

            _firstBlockScheduledDeparture =
                -1f;

            _sessionLapsCompleted =
                0;

            _sessionBlocksTaken =
                0;

            _sessionPointsGained =
                0;

            _sessionXPGained =
                0;

            _sessionLeveledUp =
                false;

            _onTimeResolved =
                false;
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // CONTINUE ON ROUTE
    // ═════════════════════════════════════════════════════════════════

    public void ContinueOnRoute(
        string routeNumber,
        string variantLetter,
        TimetableSlot slot)
    {
        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] PlayerHandoff.Instance is null — " +
                "cannot continue.");

            return;
        }


        if (
            PlayerHandoff.Instance.ShiftState !=
            PlayerHandoff.PlayerShiftState.ArrivedAtTerminal)
        {
            Debug.LogWarning(
                "[ShiftRunner] ContinueOnRoute: not waiting " +
                "at a terminal.");

            return;
        }


        if (slot == null)
        {
            Debug.LogWarning(
                $"[ShiftRunner] ContinueOnRoute: null slot " +
                $"for Route {routeNumber}.");

            return;
        }


        currentMode =
            ShiftMode.PlannedBlock;

        _sessionRouteForXP =
            routeNumber;

        _sessionBlocksTaken++;


        if (!_sessionActive)
        {
            _sessionActive =
                true;

            _firstBlockScheduledDeparture =
                slot.scheduledDeparture;

            _sessionStartRealTime =
                Time.realtimeSinceStartup;

            _sessionStartGameMin =
                SimClock.Instance != null
                    ? SimClock.Instance.AbsoluteGameMinutes
                    : 0f;

            _sessionLapsCompleted =
                0;

            _sessionPointsGained =
                0;

            _sessionXPGained =
                0;

            _sessionLeveledUp =
                false;

            _onTimeResolved =
                false;
        }


        if (slot.assignedBusID >= 0)
        {
            int npcBusID =
                slot.assignedBusID;


            var transferred =
                BusScheduler.Instance != null
                    ? BusScheduler.Instance
                        .TransferSlotToPlayer(npcBusID, slot)
                    : null;


            if (transferred != null)
            {
                if (logShiftEvents)
                {
                    Debug.Log(
                        $"[ShiftRunner] Took over Route " +
                        $"{routeNumber} from NPC busID {npcBusID} — " +
                        "remaining chain transferred.");
                }


                PlayerHandoff.Instance
                    .JoinTransferredSlot(
                        routeNumber,
                        variantLetter ?? "",
                        transferred,
                        fromBoard: true);
            }
            else
            {
                Debug.LogWarning(
                    $"[ShiftRunner] TransferSlotToPlayer failed " +
                    $"for Route {routeNumber}.");
            }
        }
        else
        {
            PlayerHandoff.Instance
                .JoinRouteWithSlot(
                    routeNumber,
                    variantLetter ?? "",
                    slot,
                    fromBoard: true);
        }


        DriverConsole.Instance?
            .SetJoinFieldsFromBoard(
                routeNumber,
                variantLetter);


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Continued onto Route " +
                $"{routeNumber}{variantLetter} dep " +
                $"{slot.scheduledDeparture:0.0}, same bus.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // LEG ARRIVED / SCORING
    // ═════════════════════════════════════════════════════════════════

    private void HandleLegArrived(
        int segmentsCompleted)
    {
        _sessionLapsCompleted++;


        if (
            _firstBlockScheduledDeparture > 0f &&
            SimClock.Instance != null &&
            !_onTimeResolved)
        {
            _firstBlockOnTime =
                SimClock.Instance.AbsoluteGameMinutes <=
                _firstBlockScheduledDeparture + 0.5f;

            _onTimeResolved =
                true;
        }


        if (PointsManager.Instance != null)
        {
            int legPoints =
                PointsManager.Instance.EndLegAndCalculate(
                    out int legXP,
                    out bool legLeveledUp);


            _sessionPointsGained +=
                legPoints;

            _sessionXPGained +=
                legXP;


            if (legLeveledUp)
                _sessionLeveledUp = true;
        }


        if (ShiftEventOverlay.Instance != null)
        {
            string routeLabel =
                PlayerHandoff.Instance != null
                    ? PlayerHandoff.Instance.ActiveRouteLabel
                    : "";


            // "Lap X of Y": Y = laps done + laps actually LEFT on this rotation (legs still queued for this
            // bus), not the route's full lap count. OnLegArrived fires before the scheduler completes the
            // leg, so the queue count is legs AFTER the one just finished.
            int lapsDone = Mathf.Max(1, segmentsCompleted);
            int pending =
                BusScheduler.Instance != null &&
                PlayerHandoff.Instance != null
                    ? BusScheduler.Instance.GetPendingLegsAfterCurrent(PlayerHandoff.Instance.PlayerBusID)
                    : 0;
            int totalLaps = lapsDone + pending;


            ShiftEventOverlay.Instance.ShowLapComplete(
                routeLabel,
                Mathf.Max(
                    1,
                    segmentsCompleted),
                totalLaps);
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // START PLANNED BLOCK
    // ═════════════════════════════════════════════════════════════════

    public void StartPlannedBlock(
        int blockIndex)
    {
        if (
            blockIndex < 0 ||
            blockIndex >= todaysSchedule.Count)
        {
            return;
        }


        var block =
            todaysSchedule[blockIndex];


        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] PlayerHandoff.Instance is null.");

            return;
        }


        if (PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Already on duty — " +
                "request relief or abandon.");

            return;
        }


        activeBlockIndex =
            blockIndex;

        currentMode =
            ShiftMode.PlannedBlock;


        PlayerHandoff.Instance
            .JoinRoute(block.routeNumber);


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Started planned block: " +
                $"{block.TimeRangeLabel} Route " +
                $"{block.routeNumber}");
        }


        SaveProgress();
    }


    // ═════════════════════════════════════════════════════════════════
    // START PLANNED BLOCK WITH SPECIFIC BUS
    // ═════════════════════════════════════════════════════════════════

    public void StartPlannedBlockWithBus(
        int blockIndex,
        int npcBusID)
    {
        if (
            blockIndex < 0 ||
            blockIndex >= todaysSchedule.Count)
        {
            return;
        }


        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] PlayerHandoff.Instance is null.");

            return;
        }


        if (PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Already on duty.");

            return;
        }


        activeBlockIndex =
            blockIndex;

        currentMode =
            ShiftMode.PlannedBlock;


        RequestPreferredBus(
            npcBusID);


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Started planned block via " +
                $"specific bus #{npcBusID}: " +
                $"{todaysSchedule[blockIndex].TimeRangeLabel} " +
                $"Route {todaysSchedule[blockIndex].routeNumber}");
        }


        SaveProgress();
    }


    // ═════════════════════════════════════════════════════════════════
    // AD-HOC SHIFT
    // ═════════════════════════════════════════════════════════════════

    public void StartAdHocShift(
        string routeNumber)
    {
        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] PlayerHandoff.Instance is null.");

            return;
        }


        if (PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Already on duty.");

            return;
        }


        activeBlockIndex =
            -1;

        currentMode =
            ShiftMode.AdHoc;


        PlayerHandoff.Instance
            .JoinRoute(routeNumber);


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Started ad-hoc shift " +
                $"on Route {routeNumber}.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // POSSESS LIVE BUS
    // ═════════════════════════════════════════════════════════════════

    public void StartByPossessingLiveBus(
        int npcBusID)
    {
        if (BusManager.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] BusManager.Instance is null.");

            return;
        }


        var record =
            BusManager.Instance
                .GetRecord(npcBusID);


        if (
            record == null ||
            record.controller == null)
        {
            Debug.LogWarning(
                $"[ShiftRunner] No live record " +
                $"for busID {npcBusID}.");

            return;
        }


        if (!_sessionActive)
        {
            _sessionActive =
                true;

            _sessionRouteForXP =
                null;

            _sessionStartRealTime =
                Time.realtimeSinceStartup;

            _sessionStartGameMin =
                SimClock.Instance != null
                    ? SimClock.Instance.AbsoluteGameMinutes
                    : 0f;

            _sessionLapsCompleted =
                0;

            _sessionBlocksTaken =
                1;

            _firstBlockScheduledDeparture =
                -1f;

            _onTimeResolved =
                false;

            _sessionPointsGained =
                0;

            _sessionXPGained =
                0;

            _sessionLeveledUp =
                false;
        }


        PossessAndAdopt(
            record.controller);


        if (
            string.IsNullOrEmpty(
                _sessionRouteForXP) &&
            PlayerHandoff.Instance != null)
        {
            _sessionRouteForXP =
                PlayerHandoff.Instance
                    .ActiveRoute;
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // PREFERRED BUS
    // ═════════════════════════════════════════════════════════════════

    public void RequestPreferredBus(
        int busID)
    {
        if (BusManager.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] BusManager.Instance is null.");

            return;
        }


        var record =
            BusManager.Instance
                .GetRecord(busID);


        if (record == null)
        {
            Debug.LogWarning(
                $"[ShiftRunner] Unknown busID {busID}.");

            return;
        }


        if (record.isActive)
        {
            PossessAndAdopt(
                record.controller);
        }
        else
        {
            _pendingRendezvousBusID =
                busID;


            var slotNow =
                BusScheduler.Instance?
                    .GetCurrentSlotForBus(busID);


            _pendingRendezvousExpectedRoute =
                slotNow?.routeNumber;


            if (logShiftEvents)
            {
                Debug.Log(
                    $"[ShiftRunner] Rendezvous pending — " +
                    $"reach Bus#{busID} at " +
                    $"{record.controller.transform.position}. " +
                    $"Expected route at selection: " +
                    $"{_pendingRendezvousExpectedRoute ?? "unknown"}.");
            }
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // RENDEZVOUS
    // ═════════════════════════════════════════════════════════════════

    private void CheckPendingRendezvous()
    {
        if (_pendingRendezvousBusID < 0)
            return;

        if (
            BusManager.Instance == null ||
            PlayerHandoff.Instance == null)
        {
            return;
        }


        var record =
            BusManager.Instance
                .GetRecord(
                    _pendingRendezvousBusID);


        if (
            record == null ||
            PlayerHandoff.Instance.playerBus == null)
        {
            return;
        }


        float dist =
            Vector3.Distance(
                PlayerHandoff.Instance
                    .playerBus.transform.position,
                record.controller.transform.position);


        if (
            dist <=
            PlayerHandoff.Instance
                .terminalArrivalRadius)
        {
            var slotNow =
                BusScheduler.Instance?
                    .GetCurrentSlotForBus(
                        _pendingRendezvousBusID);


            if (
                slotNow != null &&
                !string.IsNullOrEmpty(
                    _pendingRendezvousExpectedRoute) &&
                slotNow.routeNumber !=
                    _pendingRendezvousExpectedRoute)
            {
                Debug.LogWarning(
                    $"[ShiftRunner] Bus#" +
                    $"{_pendingRendezvousBusID}'s chain advanced " +
                    "while you were walking over — selected " +
                    $"Route {_pendingRendezvousExpectedRoute}, " +
                    $"it's now on Route {slotNow.routeNumber}. " +
                    "Possessing anyway.");
            }


            PossessAndAdopt(
                record.controller);


            _pendingRendezvousBusID =
                -1;

            _pendingRendezvousExpectedRoute =
                null;
        }
    }


    private void PossessAndAdopt(
        NPCBusController target)
    {
        if (BusSelectMenu.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] BusSelectMenu.Instance is null.");

            return;
        }


        BusSelectMenu.Instance
            .PossessFleetNumber(
                target.fleetNumber);


        if (currentMode == ShiftMode.None)
            currentMode =
                ShiftMode.AdHoc;


        if (logShiftEvents)
        {
            Debug.Log(
                $"[ShiftRunner] Possessed Bus#" +
                $"{target.busID} " +
                $"(Fleet #{target.fleetNumber}) via " +
                "BusSelectMenu.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // COMPLETE CURRENT BLOCK
    // ═════════════════════════════════════════════════════════════════

    public void CompleteCurrentBlock()
    {
        if (
            currentMode == ShiftMode.None ||
            PlayerHandoff.Instance == null ||
            !PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Not on duty — " +
                "nothing to complete.");

            return;
        }


        PlayerHandoff.Instance
            .EndCurrentLegForShiftAdvance();


        if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] Current block completed — " +
                "advancing to next planned block.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // END SHIFT
    // ═════════════════════════════════════════════════════════════════

    public void EndShiftNow()
    {
        if (
            currentMode == ShiftMode.None ||
            PlayerHandoff.Instance == null ||
            !PlayerHandoff.Instance.IsOnDuty)
        {
            Debug.LogWarning(
                "[ShiftRunner] Not on duty — nothing to end.");

            return;
        }


        PlayerHandoff.Instance
            .EndShiftFully();


        if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] Shift ended by player — " +
                "returning to depot.");
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // ABANDON
    // ═════════════════════════════════════════════════════════════════

    public void AbandonShiftEarly()
    {
        if (currentMode == ShiftMode.None)
            return;


        if (PlayerHandoff.Instance == null)
        {
            Debug.LogWarning(
                "[ShiftRunner] AbandonShiftEarly: " +
                "PlayerHandoff.Instance is null — " +
                "clearing local shift state only.");
        }
        else
        {
            int busID =
                PlayerHandoff.Instance.PlayerBusID;


            BusScheduler.Instance?
                .ReleasePlayerSlot(busID);
        }


        if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] Shift abandoned early by player.");
        }


        if (
            activeBlockIndex >= 0 &&
            activeBlockIndex <
                todaysSchedule.Count)
        {
            todaysSchedule[
                activeBlockIndex].missed =
                true;
        }


        ResetSessionState();


        SaveProgress();


        if (_regeneratePending)
        {
            _regeneratePending =
                false;


            if (logShiftEvents)
            {
                Debug.Log(
                    "[ShiftRunner] Running deferred day-roll " +
                    "regen now that the shift was abandoned.");
            }


            RegenerateSchedule();
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // BLOCK COMPLETION
    // ═════════════════════════════════════════════════════════════════

    private void MarkActiveBlockCompleted()
    {
        if (
            activeBlockIndex >= 0 &&
            activeBlockIndex <
                todaysSchedule.Count)
        {
            todaysSchedule[
                activeBlockIndex].completed =
                true;
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // BLOCK ADVANCED
    // ═════════════════════════════════════════════════════════════════

    private void HandleBlockAdvanced()
    {
        MarkActiveBlockCompleted();
    }


    // ═════════════════════════════════════════════════════════════════
    // SHIFT ENDED
    // ═════════════════════════════════════════════════════════════════

    private void HandlePlayerShiftEnded()
    {
        MarkActiveBlockCompleted();


        if (
            _sessionActive &&
            PointsManager.Instance != null)
        {
            string latenessSummary =
                null;


            var ph =
                PlayerHandoff.Instance;


            if (ph != null)
            {
                int onTime =
                    ph.OnTimeDepartureCount;

                int late =
                    ph.LateDepartureCount;

                int early =
                    ph.EarlyDepartureCount;


                int totalDep =
                    onTime +
                    late +
                    early;


                if (totalDep > 0)
                {
                    latenessSummary =
                        $"On time: {onTime}/{totalDep} departures  ·  " +
                        $"{late} late  ·  " +
                        $"{early} early";
                }
            }


            string xpBreakdown =
                $"Points this shift: {_sessionPointsGained}" +
                (
                    !string.IsNullOrEmpty(
                        latenessSummary)
                        ? $"\n{latenessSummary}"
                        : ""
                );


            float gameMinutesTaken =
                SimClock.Instance != null
                    ? SimClock.Instance.AbsoluteGameMinutes -
                      _sessionStartGameMin
                    : 0f;


            float realSecondsTaken =
                Time.realtimeSinceStartup -
                _sessionStartRealTime;


            ShiftSummaryCard.Instance?.Show(
                routeLabel:
                    _sessionRouteForXP ?? "",

                xpGained:
                    _sessionXPGained,

                totalXp:
                    PointsManager.Instance.xp,

                leveledUp:
                    _sessionLeveledUp,

                newLevel:
                    PointsManager.Instance.level,

                xpBreakdown:
                    xpBreakdown,

                lapsCompleted:
                    _sessionLapsCompleted,

                blocksTaken:
                    _sessionBlocksTaken,

                onTimeToFirstBlock:
                    _firstBlockOnTime,

                gameMinutesTaken:
                    Mathf.Max(
                        0f,
                        gameMinutesTaken),

                realSecondsTaken:
                    Mathf.Max(
                        0f,
                        realSecondsTaken));


            DriverProfile.Instance?
                .RecordShiftCompleted(
                    _sessionLapsCompleted,
                    _firstBlockOnTime);
        }


        ResetSessionState();


        activeBlockIndex =
            -1;

        currentMode =
            ShiftMode.None;

        _lastNudgedBlock =
            null;


        if (logShiftEvents)
        {
            Debug.Log(
                "[ShiftRunner] Shift ended, back to free-roam.");
        }


        SaveProgress();


        if (_regeneratePending)
        {
            _regeneratePending =
                false;


            if (logShiftEvents)
            {
                Debug.Log(
                    "[ShiftRunner] Running deferred day-roll " +
                    "regen now that the shift has ended.");
            }


            RegenerateSchedule();
        }
    }


    // ═════════════════════════════════════════════════════════════════
    // RESET SESSION
    // ═════════════════════════════════════════════════════════════════

    private void ResetSessionState()
    {
        _sessionActive =
            false;

        _firstBlockScheduledDeparture =
            -1f;

        _firstBlockOnTime =
            false;

        _sessionRouteForXP =
            null;

        _onTimeResolved =
            false;

        _sessionLapsCompleted =
            0;

        _sessionBlocksTaken =
            0;

        _sessionStartRealTime =
            0f;

        _sessionStartGameMin =
            0f;

        _sessionPointsGained =
            0;

        _sessionXPGained =
            0;

        _sessionLeveledUp =
            false;
    }
}